# ======================
# Application
# ======================
spring.application.name=gateway

# ======================
# Server Configuration
# ======================
server.port=8082
server.ssl.enabled=true
server.ssl.key-store=classpath:gateway.p12
server.ssl.key-store-password=maemae
server.ssl.key-store-type=PKCS12
# ======================
# Gateway Routes
# ======================
spring.cloud.gateway.routes[0].id=micro_service1
spring.cloud.gateway.routes[0].uri=http://localhost:8080
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/**

spring.cloud.gateway.routes[1].id=micro_service2
spring.cloud.gateway.routes[1].uri=http://localhost:8081
spring.cloud.gateway.routes[1].predicates[0]=Path=/contrat/**

# ======================
# Config Server
# ======================
spring.config.import=optional:configserver:http://localhost:8888/

# ======================
# Discovery Locator
# ======================
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

# ======================
# Logging Configuration
# ======================
logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.org.springframework.web.cors=DEBUG

# ======================
# Management Endpoints
# ======================
management.endpoints.web.exposure.include=*
management.endpoint.gateway.enabled=true

# ======================
# Web Application Type
# ======================
spring.main.web-application-type=reactive



